### ISSUE TITLE
Interactions with userEvent are not executed before happo snapshots

### ISSUE THREAD

**Issue by Q-Man** [happo/happo-plugin-storybook#95] opened 2023-05-26 12:02 UTC
I'm using Storybook in combination with `@storybook/addon-interactions`, so I can define `play` functions that perform UI interactions before the snapshot is taken.

Interactions with `fireEvent` are working correctly, they're executed before the snapshot is taken.

Interactions with `userEvent` are working in storybook, but are not executed before the snapshot is taken.

Is that unsupported or is it a bug?

I created a demo repo to demonstrate this:
https://github.com/Q-Man/happo-storybook-userevent/

Here's my code:
```jsx
import React from 'react'
import {userEvent, screen, fireEvent} from "@storybook/testing-library"

const Test = () => {
  return <div>
    <input type="radio" name="test" id="test1"/>
    <label htmlFor="test1">test1</label>
    <input type="radio" name="test" id="test2"/>
    <label htmlFor="test2">test2</label>
  </div>
}

const meta = {component: Test}

export const Default = {}

export const WithFireEvent = {
  play: async () => {
    // this is correctly executed before the snapshot
    await fireEvent.click(screen.getByLabelText('test2'))
  }
}

export const WithUserEvent = {
  play: async () => {
    // this is working in the storybook UI, but not executed before the snapshot
    await userEvent.click(screen.getByLabelText('test2'))
  }
}

export default meta
```

These are the resulting Happo snapshots:
<img width="900" alt="happo_snapshots" src="https://github.com/happo/happo-plugin-storybook/assets/53130/b91c736e-218d-4ed9-9083-59e825bb62b1">

**Comment by trotzig** [comment] 2023-05-26 15:12
Thanks for the report -- I'll have a look at this and see if I can figure out a fix after the weekend. 🙏

**Comment by trotzig** [comment] 2023-05-29 09:53
Thanks for making the reproduction repo, it's been a great help when debugging this! 🎉

It looks like this is because we are setting `pointer-events: none` on the whole document when we take screenshots. We do this to prevent spurious hover effects caused in certain environments (read: Microsoft Edge on Windows). I'm working on changing this right now.

**Comment by trotzig** [comment] 2023-05-29 10:18
I've made an update to our workers and things are looking better: 
<img width="951" alt="Screenshot 2023-05-29 at 12 15 26" src="https://github.com/happo/happo-plugin-storybook/assets/578277/2005340a-717c-4467-a4d6-4f0fa523edb5">

Thanks for filing the issue and the help with the repo! 

At first I thought this was because of the event happening asynchronously, so I did some work on happo-plugin-storybook as well, there's a new version with slightly better behavior around user events: https://github.com/happo/happo-plugin-storybook/releases/tag/v3.2.4 . Note however that this release isn't needed in your case, the worker update I did is enough to make the user event work.

**Comment by trotzig** [comment] 2023-05-29 10:19
Oh, forgot to mention: this is fixed in Chrome and Firefox for now. Safari will be updated in our next release cycle which should be in the next couple of weeks.

**Comment by Q-Man** [comment] 2023-05-30 03:50
Thank you for the quick fix, it's working. 🎉 

I observed another thing with `userEvent`, opened another ticket for this:
https://github.com/happo/happo-plugin-storybook/issues/97

**Comment by trotzig** [comment] 2023-06-02 17:32
It turns out that `pointer-events:none` was quite important after all, so removing it led to a few unwanted side-effects. To make it possible to use `userEvent`s however, I've added a new configuration option in .happo.js: `allowPointerEvents: true`. See documentation here: https://docs.happo.io/docs/configuration#target-allowpointerevents

I tried hard to avoid having to use a configuration option, but it ended up being really tricky to avoid all types of spurious hover effects caused by allowing pointer-events. 🤷‍♂️

**Closed** 2023-06-02 17:32 UTC
